let book = await MiyacoGlobalBooks.createAccountingBook("Regression book");
assert await MiyacoGlobalBooks.isCallerBookAdmin(book);
assert await MiyacoGlobalBooks.isCallerPermanentAdmin(book);
func ok(result : MiyacoGlobalBooks.MutResult) { switch result { case (#ok(_)) {}; case (#err(message)) { Runtime.trap(message) } } };
func rejected(result : MiyacoGlobalBooks.MutResult) { switch result { case (#err(_)) {}; case _ { Runtime.trap("Expected rejection") } } };
let owner = (await MiyacoGlobalBooks.getUserBooks())[0].admin;
let item : MiyacoGlobalBooks.InventoryItem = {
  id = "shaft"; name = "Shaft"; brand = "Test"; productType = "Shaft"; supplier = "Supplier";
  quantity = 10; costPrice = 50.0; sellingPrice = 60.0; unitsPerCarton = 1; locationId = "";
  variants = []; bookId = book; approved = false; highestEverQuantity = 10; createdAt = 1;
};
ok(await MiyacoGlobalBooks.addInventoryItem(item));
let sale : MiyacoGlobalBooks.Transaction = {
  id = "sale-1"; date = 2; customerName = "Ada"; phone = "08000000000"; email = "";
  brand = "Test"; productType = "Shaft"; typeSubtype = "Sales"; itemName = "Shaft";
  cartons = 1; unitsPerCarton = 1; pricePerCarton = 60.0; amount = 9999.0;
  sellingPriceAtSale = 9999.0; costPriceAtSale = 0.0; currency = "NGN"; paymentMethod = "cash";
  notes = ""; bookId = book; createdBy = owner; approved = false; approvalProcessed = false;
};
ok(await MiyacoGlobalBooks.addTransaction(sale));
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 10;
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 9;
let customers1 = await MiyacoGlobalBooks.getCustomers(book);
assert customers1.size() == 1;
assert customers1[0].totalSpent == 60.0;
assert customers1[0].outstandingDebt == 0.0;
rejected(await MiyacoGlobalBooks.addTransaction(sale));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 9;
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "credit-1"; typeSubtype = "Credit Sales"; customerName = " ada "; phone = "08011111111"; date = 3 }));
let customers2 = await MiyacoGlobalBooks.getCustomers(book);
assert customers2.size() == 1;
assert customers2[0].outstandingDebt == 60.0;
assert customers2[0].totalSpent == 120.0;
assert customers2[0].transactionCount == 2;
assert customers2[0].phone == "08011111111";
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 8;
rejected(await MiyacoGlobalBooks.addTransaction({ sale with id = "oversell"; cartons = 9 }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 8;
assert (await MiyacoGlobalBooks.getCustomers(book))[0].transactionCount == 2;
rejected(await MiyacoGlobalBooks.addTransaction({ sale with id = "zero"; cartons = 0 }));
rejected(await MiyacoGlobalBooks.approveInventoryItem("shaft"));
rejected(await MiyacoGlobalBooks.rejectTransaction("sale-1"));
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "purchase-1"; typeSubtype = "Purchases"; customerName = "Supplier"; cartons = 2; unitsPerCarton = 5; pricePerCarton = 250.0 }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 18;
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "carton-sale"; cartons = 1; unitsPerCarton = 5; pricePerCarton = 300.0 }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 13;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 60;
switch (await MiyacoGlobalBooks.getCustomerStatement(book, "Ada")) {
  case (#ok(statement)) { assert statement.currentBalance == 60.0; assert statement.totalPurchases == 420.0 };
  case _ { assert false };
};
await MiyacoGlobalBooks.setCustomerPhoto(book, "Ada", "data:image/png;base64,dGVzdA==");
assert (await MiyacoGlobalBooks.getCustomerPhoto(book, "ada")) == "data:image/png;base64,dGVzdA==";
switch (await MiyacoGlobalBooks.getAnalyticsExtended(book, "all")) { case (#ok(_)) {}; case _ { assert false } };
Debug.print("PASS: book-admin access, 50/60 profit, stock, duplicate/oversell/zero rejection, cartons, customer profiles, credit debt, photos and analytics");
actor Staff {
  public func join(bookId : Text) : async MiyacoGlobalBooks.JoinRequestResult { await MiyacoGlobalBooks.requestJoinBook(bookId) };
  public func sell(tx : MiyacoGlobalBooks.Transaction) : async MiyacoGlobalBooks.MutResult { await MiyacoGlobalBooks.addTransaction(tx) };
  public func isAdmin(bookId : Text) : async Bool { await MiyacoGlobalBooks.isCallerBookAdmin(bookId) };
  public func inventory(bookId : Text) : async [MiyacoGlobalBooks.InventoryItem] { await MiyacoGlobalBooks.getInventory(bookId) };
  public func transactions(bookId : Text) : async [MiyacoGlobalBooks.Transaction] { await MiyacoGlobalBooks.getTransactions(bookId) };
  public func detail(id : Text) : async MiyacoGlobalBooks.Settlement { await MiyacoGlobalBooks.getTransactionDetail(id) };
  public func pay(id : Text) : async MiyacoGlobalBooks.MutResult { await MiyacoGlobalBooks.recordCreditPayment(id, "staff-pay", 10.0, "cash", "") };
  public func product(id : Text) : async MiyacoGlobalBooks.MutResult { await MiyacoGlobalBooks.setProductDetails(id, { description = "Changed"; image = "" }) };
  public func voidTx(id : Text) : async MiyacoGlobalBooks.MutResult { await MiyacoGlobalBooks.voidTransaction(id, 0, "unauthorized") };
};
ok(await Staff.join(book));
let pendingJoin = (await MiyacoGlobalBooks.getPendingJoinRequests())[0];
ok(await MiyacoGlobalBooks.approveJoinRequest(pendingJoin.user.toText() # "-" # book, false));
assert not (await Staff.isAdmin(book));
ok(await Staff.sell({ sale with id = "staff-sale"; customerName = "Bola" }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 13;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 60;
assert (await MiyacoGlobalBooks.getCustomers(book)).size() == 1;
assert (await MiyacoGlobalBooks.getPendingTransactions(book)).size() == 1;
ok(await MiyacoGlobalBooks.approveTransaction("staff-sale"));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 12;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 70;
assert (await MiyacoGlobalBooks.getCustomers(book)).size() == 2;
rejected(await MiyacoGlobalBooks.approveTransaction("staff-sale"));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 12;
Debug.print("PASS: staff approval posts stock, profit and customer exactly once; pending entries excluded");
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "credit-2"; typeSubtype = "Credit Sales" }));
assert (await MiyacoGlobalBooks.getOutstandingCredits(book)).customersWithDebt == 1;
assert (await MiyacoGlobalBooks.getOutstandingCredits(book)).totalOutstanding == 120.0;
switch (await MiyacoGlobalBooks.updateBookSettings(book, { bookId = book; baseCurrency = "NGN"; exchangeRate = 100.0; hideCostPricesFromNonAdmins = false; scheduledSummaryFrequency = "never"; lastSummaryDate = 0 })) {
  case (#ok(_)) {}; case _ { assert false };
};
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "usd-sale"; currency = "USD"; pricePerCarton = 0.6 }));
let usdTx = (await MiyacoGlobalBooks.getTransactions(book)).find(func(tx : MiyacoGlobalBooks.Transaction) : Bool { tx.id == "usd-sale" });
switch usdTx { case (?tx) { assert tx.amount == 60.0; assert tx.currency == "NGN" }; case null { assert false } };
Debug.print("PASS: debt counts unique customers; USD sale converted to NGN at saved rate");

let stockBeforePayments = (await MiyacoGlobalBooks.getInventory(book))[0].quantity;
let beforeProfit = (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin;
ok(await MiyacoGlobalBooks.recordCreditPayment("credit-1", "p1", 20.0, "transfer", "first installment"));
assert (await MiyacoGlobalBooks.getTransactionDetail("credit-1")).balance == 40.0;
assert (await MiyacoGlobalBooks.getTransactionDetail("credit-1")).profit == 0.0;
rejected(await MiyacoGlobalBooks.recordCreditPayment("credit-1", "p1", 20.0, "transfer", "retry"));
rejected(await MiyacoGlobalBooks.recordCreditPayment("credit-1", "p-too-big", 41.0, "cash", ""));
ok(await MiyacoGlobalBooks.recordCreditPayment("credit-1", "p2", 30.0, "cash", "cost covered"));
assert (await MiyacoGlobalBooks.getTransactionDetail("credit-1")).profit == 0.0;
ok(await MiyacoGlobalBooks.recordCreditPayment("credit-1", "p3", 5.0, "cash", "profit starts"));
assert (await MiyacoGlobalBooks.getTransactionDetail("credit-1")).profit == 5.0;
ok(await MiyacoGlobalBooks.recordCreditPayment("credit-1", "p4", 5.0, "cash", "settled"));
let settled = await MiyacoGlobalBooks.getTransactionDetail("credit-1");
assert settled.balance == 0.0 and settled.profit == 10.0 and settled.payments.size() == 4;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == beforeProfit + 10;
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == stockBeforePayments;
assert (await MiyacoGlobalBooks.getOutstandingCredits(book)).totalOutstanding == 60.0;
ok(await MiyacoGlobalBooks.refundCreditPayment("credit-1", "refund1", 5.0, "Payment entry corrected"));
assert (await MiyacoGlobalBooks.getTransactionDetail("credit-1")).balance == 5.0;
assert (await MiyacoGlobalBooks.getTransactionDetail("credit-1")).profit == 5.0;
Debug.print("PASS: full/partial payments, cost recovery, refund correction, duplicate/overpayment guards and stock unchanged");

for (i in (await Staff.inventory(book)).values()) { assert i.costPrice == 0.0 and i.supplier == "" };
for (t in (await Staff.transactions(book)).values()) { assert t.costPriceAtSale == 0.0 and t.typeSubtype != "Purchases" };
assert (await Staff.detail("credit-1")).profit == 0.0;
assert (await Staff.detail("credit-1")).history.size() == 0;
rejected(await Staff.pay("credit-1"));
rejected(await Staff.product("shaft"));
rejected(await Staff.voidTx("sale-1"));
Debug.print("PASS: staff API responses redact costs/profit and block payment/product/void mutations");

let largeSale = { sale with id = "return-test"; typeSubtype = "Credit Sales"; cartons = 2 };
ok(await MiyacoGlobalBooks.addTransaction(largeSale));
ok(await MiyacoGlobalBooks.recordCreditPayment("return-test", "return-pay", 120.0, "cash", ""));
let original = await MiyacoGlobalBooks.getTransactionDetail("return-test");
let beforeReturnStock = (await MiyacoGlobalBooks.getInventory(book))[0].quantity;
ok(await MiyacoGlobalBooks.amendTransaction({ original.transaction with cartons = 1 }, 0, "One unit returned, resaleable"));
let corrected = await MiyacoGlobalBooks.getTransactionDetail("return-test");
assert corrected.refundDue == 60.0 and corrected.profit == 10.0;
assert corrected.history.size() == 1 and corrected.history[0].before.amount == 120.0 and corrected.history[0].after.amount == 60.0;
assert corrected.history[0].actorPrincipal == owner;
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == beforeReturnStock + 1;
rejected(await MiyacoGlobalBooks.amendTransaction(original.transaction, 0, "stale"));
ok(await MiyacoGlobalBooks.refundCreditPayment("return-test", "return-refund", 60.0, "Returned one unit"));
assert (await MiyacoGlobalBooks.getTransactionDetail("return-test")).refundDue == 0.0;
ok(await MiyacoGlobalBooks.voidTransaction("return-test", 1, "Remaining unit returned"));
let voided = await MiyacoGlobalBooks.getTransactionDetail("return-test");
assert voided.voided and voided.refundDue == 60.0 and voided.history.size() == 2;
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == beforeReturnStock + 2;
ok(await MiyacoGlobalBooks.refundCreditPayment("return-test", "void-refund", 60.0, "Final refund issued"));
assert (await MiyacoGlobalBooks.getTransactionDetail("return-test")).refundDue == 0.0;
assert (await MiyacoGlobalBooks.getVoidedTransactions(book)).size() == 1;
rejected(await MiyacoGlobalBooks.addTransaction(largeSale));
let beforeDeleteStock = (await MiyacoGlobalBooks.getInventory(book))[0].quantity;
let beforeDeleteProfit = (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin;
ok(await MiyacoGlobalBooks.deleteTransaction("sale-1"));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == beforeDeleteStock + 1;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == beforeDeleteProfit - 10;
Debug.print("PASS: partial returns, stale-edit rejection, immutable history, void/refund archive and legacy delete recalculate stock and profit");

let expense : MiyacoGlobalBooks.Expense = { id = "rent"; date = 4; category = "Rent"; description = "Test rent"; amount = 12.0; bookId = book; createdBy = owner; approved = false };
ok(await MiyacoGlobalBooks.addExpense(expense));
rejected(await MiyacoGlobalBooks.addExpense(expense));
let finance = await MiyacoGlobalBooks.getFinancialSummary(book, 0, 999999999999999999999);
assert finance.netProfit == finance.grossProfit - 12.0;
assert finance.grossProfit == (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin.toFloat();
ok(await MiyacoGlobalBooks.amendExpense({ expense with amount = 5.0 }, 12.0, "Overstated", false));
let finance2 = await MiyacoGlobalBooks.getFinancialSummary(book, 0, 999999999999999999999);
assert finance2.netProfit == finance2.grossProfit - 5.0;
ok(await MiyacoGlobalBooks.setStockPolicy("shaft", { enabled = true; minimumUnits = 100; targetUnits = 200; leadDays = 10 }));
assert (await MiyacoGlobalBooks.getLowStockAlerts(book)).size() == 1;
ok(await MiyacoGlobalBooks.setStockPolicy("shaft", { enabled = false; minimumUnits = 100; targetUnits = 200; leadDays = 10 }));
assert (await MiyacoGlobalBooks.getLowStockAlerts(book)).size() == 0;
ok(await MiyacoGlobalBooks.setProductDetails("shaft", { description = "Toyota shaft, verify fitment"; image = "" }));
assert (await MiyacoGlobalBooks.getProductDetails("shaft")).description == "Toyota shaft, verify fitment";
Debug.print("PASS: net profit after expenses, expense correction, configurable alerts and product details");

assert (await MiyacoGlobalBooks.getTransactionDetail("sale-1")).refundDue == 60.0;
ok(await MiyacoGlobalBooks.refundCreditPayment("sale-1", "cash-refund", 60.0, "Returned cash to customer"));
assert (await MiyacoGlobalBooks.getTransactionDetail("sale-1")).refundDue == 0.0;
rejected(await MiyacoGlobalBooks.refundCreditPayment("sale-1", "cash-over-refund", 1.0, "Too much"));
let cashTx = (await MiyacoGlobalBooks.getTransactionDetail("carton-sale")).transaction;
ok(await MiyacoGlobalBooks.amendTransaction({ cashTx with unitsPerCarton = 4; pricePerCarton = 240.0 }, 0, "One unit returned"));
assert (await MiyacoGlobalBooks.getTransactionDetail("carton-sale")).refundDue == 60.0;
ok(await MiyacoGlobalBooks.refundCreditPayment("carton-sale", "cash-partial-refund", 20.0, "Part refund issued"));
assert (await MiyacoGlobalBooks.getTransactionDetail("carton-sale")).refundDue == 40.0;
Debug.print("PASS: cash-sale full and partial returns track unissued refunds without creating revenue");

let weighted = await MiyacoGlobalBooks.createAccountingBook("Weighted-cost regression");
ok(await MiyacoGlobalBooks.addInventoryItem({ item with id = "weighted-item"; bookId = weighted; quantity = 2 }));
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "weighted-sale"; bookId = weighted }));
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "weighted-purchase"; bookId = weighted; typeSubtype = "Purchases"; pricePerCarton = 70.0 }));
assert (await MiyacoGlobalBooks.getInventory(weighted))[0].costPrice == 60.0;
let w = await MiyacoGlobalBooks.getTransactionDetail("weighted-sale");
ok(await MiyacoGlobalBooks.amendTransaction({ w.transaction with notes = "Contact corrected" }, 0, "Note only"));
assert (await MiyacoGlobalBooks.getInventory(weighted))[0].costPrice == 60.0;
ok(await MiyacoGlobalBooks.amendTransaction({ w.transaction with cartons = 2 }, 1, "Extra unit delivered"));
assert (await MiyacoGlobalBooks.getTransactionDetail("weighted-sale")).transaction.costPriceAtSale == 55.0;
assert (await MiyacoGlobalBooks.getInventory(weighted))[0].quantity == 1;
Debug.print("PASS: note-only edits preserve inventory valuation; quantity increases use the correct additional-unit cost");
