let book = await MiyacoGlobalBooks.createAccountingBook("Regression book");
assert await MiyacoGlobalBooks.isCallerBookAdmin(book);
assert await MiyacoGlobalBooks.isCallerPermanentAdmin(book);
func ok(result : MiyacoGlobalBooks.MutResult) { switch result { case (#ok(_)) {}; case (#err(message)) { Runtime.trap(message) } } };
func rejected(result : MiyacoGlobalBooks.MutResult) { switch result { case (#err(_)) {}; case _ { Runtime.trap("Expected rejection") } } };
let owner = (await MiyacoGlobalBooks.getUserBooks())[0].admin;
let item : MiyacoGlobalBooks.InventoryItem = {
  id = "shaft"; name = "Shaft"; brand = "Test"; productType = "Shaft"; supplier = "Supplier";
  quantity = 10; costPrice = 50.0; sellingPrice = 60.0; unitsPerCarton = 1; locationId = "";
  variants = []; bookId = book; approved = false; highestEverQuantity = 10; createdAt = 1;
};
ok(await MiyacoGlobalBooks.addInventoryItem(item));
let sale : MiyacoGlobalBooks.Transaction = {
  id = "sale-1"; date = 2; customerName = "Ada"; phone = "08000000000"; email = "";
  brand = "Test"; productType = "Shaft"; typeSubtype = "Sales"; itemName = "Shaft";
  cartons = 1; unitsPerCarton = 1; pricePerCarton = 60.0; amount = 9999.0;
  sellingPriceAtSale = 9999.0; costPriceAtSale = 0.0; currency = "NGN"; paymentMethod = "cash";
  notes = ""; bookId = book; createdBy = owner; approved = false; approvalProcessed = false;
};
ok(await MiyacoGlobalBooks.addTransaction(sale));
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 10;
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 9;
let customers1 = await MiyacoGlobalBooks.getCustomers(book);
assert customers1.size() == 1;
assert customers1[0].totalSpent == 60.0;
assert customers1[0].outstandingDebt == 0.0;
rejected(await MiyacoGlobalBooks.addTransaction(sale));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 9;
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "credit-1"; typeSubtype = "Credit Sales"; customerName = " ada "; phone = "08011111111"; date = 3 }));
let customers2 = await MiyacoGlobalBooks.getCustomers(book);
assert customers2.size() == 1;
assert customers2[0].outstandingDebt == 60.0;
assert customers2[0].totalSpent == 120.0;
assert customers2[0].transactionCount == 2;
assert customers2[0].phone == "08011111111";
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 8;
rejected(await MiyacoGlobalBooks.addTransaction({ sale with id = "oversell"; cartons = 9 }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 8;
assert (await MiyacoGlobalBooks.getCustomers(book))[0].transactionCount == 2;
rejected(await MiyacoGlobalBooks.addTransaction({ sale with id = "zero"; cartons = 0 }));
rejected(await MiyacoGlobalBooks.approveInventoryItem("shaft"));
rejected(await MiyacoGlobalBooks.rejectTransaction("sale-1"));
rejected(await MiyacoGlobalBooks.deleteTransaction("sale-1"));
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "purchase-1"; typeSubtype = "Purchases"; customerName = "Supplier"; cartons = 2; unitsPerCarton = 5; pricePerCarton = 250.0 }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 18;
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "carton-sale"; cartons = 1; unitsPerCarton = 5; pricePerCarton = 300.0 }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 13;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 70;
switch (await MiyacoGlobalBooks.getCustomerStatement(book, "Ada")) {
  case (#ok(statement)) { assert statement.currentBalance == 60.0; assert statement.totalPurchases == 420.0 };
  case _ { assert false };
};
await MiyacoGlobalBooks.setCustomerPhoto(book, "Ada", "data:image/png;base64,dGVzdA==");
assert (await MiyacoGlobalBooks.getCustomerPhoto(book, "ada")) == "data:image/png;base64,dGVzdA==";
switch (await MiyacoGlobalBooks.getAnalyticsExtended(book, "all")) { case (#ok(_)) {}; case _ { assert false } };
Debug.print("PASS: book-admin access, 50/60 profit, stock, duplicate/oversell/zero rejection, cartons, customer profiles, credit debt, photos and analytics");
actor Staff {
  public func join(bookId : Text) : async MiyacoGlobalBooks.JoinRequestResult { await MiyacoGlobalBooks.requestJoinBook(bookId) };
  public func sell(tx : MiyacoGlobalBooks.Transaction) : async MiyacoGlobalBooks.MutResult { await MiyacoGlobalBooks.addTransaction(tx) };
  public func isAdmin(bookId : Text) : async Bool { await MiyacoGlobalBooks.isCallerBookAdmin(bookId) };
};
ok(await Staff.join(book));
let pendingJoin = (await MiyacoGlobalBooks.getPendingJoinRequests())[0];
ok(await MiyacoGlobalBooks.approveJoinRequest(pendingJoin.user.toText() # "-" # book, false));
assert not (await Staff.isAdmin(book));
ok(await Staff.sell({ sale with id = "staff-sale"; customerName = "Bola" }));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 13;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 70;
assert (await MiyacoGlobalBooks.getCustomers(book)).size() == 1;
assert (await MiyacoGlobalBooks.getPendingTransactions(book)).size() == 1;
ok(await MiyacoGlobalBooks.approveTransaction("staff-sale"));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 12;
assert (await MiyacoGlobalBooks.getDashboardMetrics(book)).grossMargin == 80;
assert (await MiyacoGlobalBooks.getCustomers(book)).size() == 2;
rejected(await MiyacoGlobalBooks.approveTransaction("staff-sale"));
assert (await MiyacoGlobalBooks.getInventory(book))[0].quantity == 12;
Debug.print("PASS: staff approval posts stock, profit and customer exactly once; pending entries excluded");
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "credit-2"; typeSubtype = "Credit Sales" }));
assert (await MiyacoGlobalBooks.getOutstandingCredits(book)).customersWithDebt == 1;
assert (await MiyacoGlobalBooks.getOutstandingCredits(book)).totalOutstanding == 120.0;
switch (await MiyacoGlobalBooks.updateBookSettings(book, { bookId = book; baseCurrency = "NGN"; exchangeRate = 100.0; hideCostPricesFromNonAdmins = false; scheduledSummaryFrequency = "never"; lastSummaryDate = 0 })) {
  case (#ok(_)) {}; case _ { assert false };
};
ok(await MiyacoGlobalBooks.addTransaction({ sale with id = "usd-sale"; currency = "USD"; pricePerCarton = 0.6 }));
let usdTx = (await MiyacoGlobalBooks.getTransactions(book)).find(func(tx : MiyacoGlobalBooks.Transaction) : Bool { tx.id == "usd-sale" });
switch usdTx { case (?tx) { assert tx.amount == 60.0; assert tx.currency == "NGN" }; case null { assert false } };
Debug.print("PASS: debt counts unique customers; USD sale converted to NGN at saved rate");
