/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'bookId' : IDL.Text,
  'email' : IDL.Text,
  'outstandingDebt' : IDL.Float64,
  'totalSpent' : IDL.Float64,
  'lastTransactionDate' : Time,
  'brand' : IDL.Text,
  'phone' : IDL.Text,
  'transactions' : IDL.Vec(IDL.Text),
  'transactionCount' : IDL.Nat,
});
export const MutResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'bookId' : IDL.Text,
  'approved' : IDL.Bool,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'supplier' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'sellingPrice' : IDL.Float64,
  'bookId' : IDL.Text,
  'variants' : IDL.Vec(IDL.Text),
  'productType' : IDL.Text,
  'highestEverQuantity' : IDL.Nat,
  'approved' : IDL.Bool,
  'locationId' : IDL.Text,
  'unitsPerCarton' : IDL.Nat,
  'quantity' : IDL.Nat,
  'brand' : IDL.Text,
  'costPrice' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'sellingPriceAtSale' : IDL.Float64,
  'costPriceAtSale' : IDL.Float64,
  'paymentMethod' : IDL.Text,
  'typeSubtype' : IDL.Text,
  'date' : Time,
  'createdBy' : IDL.Principal,
  'bookId' : IDL.Text,
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'approved' : IDL.Bool,
  'approvalProcessed' : IDL.Bool,
  'currency' : IDL.Text,
  'notes' : IDL.Text,
  'unitsPerCarton' : IDL.Nat,
  'itemName' : IDL.Text,
  'brand' : IDL.Text,
  'phone' : IDL.Text,
  'cartons' : IDL.Nat,
  'amount' : IDL.Float64,
  'pricePerCarton' : IDL.Float64,
});
export const JoinRequestResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgingBucket = IDL.Record({
  'count' : IDL.Nat,
  'bucketLabel' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'transactions' : IDL.Vec(Transaction),
});
export const AccountingBook = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Principal),
  'admin' : IDL.Principal,
  'adminMembers' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const JoinRequest = IDL.Record({
  'status' : ApprovalStatus,
  'user' : IDL.Principal,
  'bookId' : IDL.Text,
  'requestedAt' : Time,
});
export const BranchComparisonItem = IDL.Record({
  'totalValue' : IDL.Float64,
  'salesVolume' : IDL.Float64,
  'totalItems' : IDL.Nat,
  'locationName' : IDL.Text,
});
export const ApprovalTurnaround = IDL.Record({
  'fastestHours' : IDL.Float64,
  'slowestHours' : IDL.Float64,
  'avgHours' : IDL.Float64,
  'totalApproved' : IDL.Nat,
  'totalRejected' : IDL.Nat,
});
export const ExpenseByCategoryItem = IDL.Record({
  'pct' : IDL.Float64,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const BreakEven = IDL.Record({
  'currentRevenue' : IDL.Float64,
  'surplus' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
  'requiredRevenue' : IDL.Float64,
});
export const SalesVelocityItem = IDL.Record({
  'avgUnitsPerDay' : IDL.Float64,
  'itemName' : IDL.Text,
  'totalUnits' : IDL.Nat,
});
export const TransactionErrorRate = IDL.Record({
  'errorRate' : IDL.Float64,
  'totalApproved' : IDL.Nat,
  'totalRejected' : IDL.Nat,
  'totalSubmitted' : IDL.Nat,
});
export const PeakPeriod = IDL.Record({
  'period' : IDL.Text,
  'rank' : IDL.Nat,
  'volume' : IDL.Float64,
});
export const MarginTrendPoint = IDL.Record({
  'period' : IDL.Text,
  'grossMargin' : IDL.Float64,
  'grossMarginPct' : IDL.Float64,
});
export const ForecastPoint = IDL.Record({
  'period' : IDL.Text,
  'projected' : IDL.Float64,
});
export const CustomerCLVItem = IDL.Record({
  'customerName' : IDL.Text,
  'firstTransactionDate' : IDL.Int,
  'totalRevenue' : IDL.Float64,
  'totalTransactions' : IDL.Nat,
});
export const ProfitByProductItem = IDL.Record({
  'grossProfit' : IDL.Float64,
  'itemName' : IDL.Text,
  'units' : IDL.Nat,
  'margin' : IDL.Float64,
});
export const SalesTrendPoint = IDL.Record({
  'revenue' : IDL.Float64,
  'period' : IDL.Text,
  'cost' : IDL.Float64,
  'profit' : IDL.Float64,
});
export const UserActivityItem = IDL.Record({
  'userName' : IDL.Text,
  'actionCount' : IDL.Nat,
  'principalText' : IDL.Text,
  'lastActionDate' : IDL.Int,
});
export const StockTurnoverItem = IDL.Record({
  'turnoverRate' : IDL.Float64,
  'timesRestocked' : IDL.Nat,
  'itemName' : IDL.Text,
});
export const CogsItem = IDL.Record({
  'grossProfit' : IDL.Float64,
  'totalCost' : IDL.Float64,
  'itemName' : IDL.Text,
  'totalRevenue' : IDL.Float64,
});
export const RepeatVsNewItem = IDL.Record({
  'repeatCount' : IDL.Nat,
  'repeatPct' : IDL.Float64,
  'period' : IDL.Text,
  'newCount' : IDL.Nat,
});
export const DeadStockItem = IDL.Record({
  'itemName' : IDL.Text,
  'daysSinceLastSale' : IDL.Nat,
  'currentQty' : IDL.Nat,
});
export const TopCustomerByProfit = IDL.Record({
  'customerName' : IDL.Text,
  'grossProfit' : IDL.Float64,
  'totalRevenue' : IDL.Float64,
});
export const AnalyticsExtended = IDL.Record({
  'branchComparison' : IDL.Vec(BranchComparisonItem),
  'approvalTurnaround' : ApprovalTurnaround,
  'expenseByCategory' : IDL.Vec(ExpenseByCategoryItem),
  'breakEven' : BreakEven,
  'salesVelocity' : IDL.Vec(SalesVelocityItem),
  'transactionErrorRate' : TransactionErrorRate,
  'peakPeriods' : IDL.Vec(PeakPeriod),
  'marginTrend' : IDL.Vec(MarginTrendPoint),
  'revenueForecast' : IDL.Vec(ForecastPoint),
  'customerCLV' : IDL.Vec(CustomerCLVItem),
  'profitByProduct' : IDL.Vec(ProfitByProductItem),
  'salesTrend' : IDL.Vec(SalesTrendPoint),
  'userActivity' : IDL.Vec(UserActivityItem),
  'stockTurnover' : IDL.Vec(StockTurnoverItem),
  'cogsBreakdown' : IDL.Vec(CogsItem),
  'repeatVsNewRatio' : IDL.Vec(RepeatVsNewItem),
  'deadStock' : IDL.Vec(DeadStockItem),
  'topCustomersByProfit' : IDL.Vec(TopCustomerByProfit),
  'debtAging' : IDL.Vec(AgingBucket),
});
export const AuditLogEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'actorName' : IDL.Text,
  'bookId' : IDL.Text,
  'timestamp' : IDL.Int,
  'targetType' : IDL.Text,
  'details' : IDL.Text,
  'actorPrincipal' : IDL.Text,
  'targetId' : IDL.Text,
});
export const BookSettings = IDL.Record({
  'hideCostPricesFromNonAdmins' : IDL.Bool,
  'baseCurrency' : IDL.Text,
  'scheduledSummaryFrequency' : IDL.Text,
  'bookId' : IDL.Text,
  'exchangeRate' : IDL.Float64,
  'lastSummaryDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'phone' : IDL.Text,
});
export const CustomerStatement = IDL.Record({
  'customerName' : IDL.Text,
  'currentBalance' : IDL.Float64,
  'totalPayments' : IDL.Float64,
  'totalPurchases' : IDL.Float64,
  'transactions' : IDL.Vec(Transaction),
});
export const DraftPurchaseOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'inventoryItemId' : IDL.Text,
  'suggestedQuantity' : IDL.Nat,
  'bookId' : IDL.Text,
  'currentQuantity' : IDL.Nat,
  'triggeredAt' : IDL.Int,
  'itemName' : IDL.Text,
});
export const FinancialSummary = IDL.Record({
  'grossProfit' : IDL.Float64,
  'expenses' : IDL.Float64,
  'marginPercent' : IDL.Float64,
  'receipts' : IDL.Float64,
  'netProfit' : IDL.Float64,
});
export const InventoryTransfer = IDL.Record({
  'id' : IDL.Text,
  'itemId' : IDL.Text,
  'toLocationId' : IDL.Text,
  'unit' : IDL.Text,
  'bookId' : IDL.Text,
  'fromLocationId' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'transferredAt' : Time,
  'transferredBy' : IDL.Principal,
});
export const Location = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'bookId' : IDL.Text,
});
export const ScheduledSummary = IDL.Record({
  'id' : IDL.Text,
  'topItemNames' : IDL.Vec(IDL.Text),
  'grossMargin' : IDL.Float64,
  'generatedAt' : IDL.Int,
  'topCustomerNames' : IDL.Vec(IDL.Text),
  'bookId' : IDL.Text,
  'totalExpenses' : IDL.Float64,
  'periodLabel' : IDL.Text,
  'totalInflows' : IDL.Float64,
  'transactionCount' : IDL.Nat,
});
export const ProductDetails = IDL.Record({
  'description' : IDL.Text,
  'image' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'method' : IDL.Text,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'recordedBy' : IDL.Principal,
  'amount' : IDL.Float64,
  'transactionId' : IDL.Text,
});
export const Revision = IDL.Record({
  'action' : IDL.Text,
  'actorName' : IDL.Text,
  'after' : Transaction,
  'before' : Transaction,
  'timestamp' : IDL.Int,
  'actorPrincipal' : IDL.Principal,
  'revision' : IDL.Nat,
  'reason' : IDL.Text,
});
export const Settlement = IDL.Record({
  'balance' : IDL.Float64,
  'payments' : IDL.Vec(Payment),
  'paid' : IDL.Float64,
  'transaction' : Transaction,
  'voided' : IDL.Bool,
  'history' : IDL.Vec(Revision),
  'refundDue' : IDL.Float64,
  'profit' : IDL.Float64,
  'revision' : IDL.Nat,
});
export const StockPolicy = IDL.Record({
  'leadDays' : IDL.Nat,
  'minimumUnits' : IDL.Nat,
  'targetUnits' : IDL.Nat,
  'enabled' : IDL.Bool,
});
export const SystemSettings = IDL.Record({
  'multiStore' : IDL.Bool,
  'exchangeRate' : IDL.Float64,
  'companyInfo' : IDL.Text,
  'taxRate' : IDL.Float64,
  'currencyRounding' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([Customer], [MutResult], []),
  'addExpense' : IDL.Func([Expense], [MutResult], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [MutResult], []),
  'addTransaction' : IDL.Func([Transaction], [MutResult], []),
  'amendExpense' : IDL.Func(
      [Expense, IDL.Float64, IDL.Text, IDL.Bool],
      [MutResult],
      [],
    ),
  'amendTransaction' : IDL.Func(
      [Transaction, IDL.Nat, IDL.Text],
      [MutResult],
      [],
    ),
  'approveExpense' : IDL.Func([IDL.Text], [MutResult], []),
  'approveInventoryItem' : IDL.Func([IDL.Text], [MutResult], []),
  'approveJoinRequest' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [JoinRequestResult],
      [],
    ),
  'approveTransaction' : IDL.Func([IDL.Text], [MutResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeUserRole' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [JoinRequestResult],
      [],
    ),
  'createAccountingBook' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createLocation' : IDL.Func([IDL.Text, IDL.Text], [MutResult], []),
  'deleteBook' : IDL.Func([IDL.Text], [JoinRequestResult], []),
  'deleteLocation' : IDL.Func([IDL.Text, IDL.Text], [MutResult], []),
  'deleteTransaction' : IDL.Func([IDL.Text], [MutResult], []),
  'dismissDraftPurchaseOrder' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAgingReport' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AgingBucket), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAllBooks' : IDL.Func([], [IDL.Vec(AccountingBook)], ['query']),
  'getAllJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
  'getAnalyticsExtended' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AnalyticsExtended, 'err' : IDL.Text })],
      ['query'],
    ),
  'getAuditLog' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AuditLogEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getBookMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getBookMembersWithNames' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getBookSettings' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : BookSettings, 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerNames' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getCustomerPhoto' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
  'getCustomerStatement' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : CustomerStatement, 'err' : IDL.Text })],
      ['query'],
    ),
  'getCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'getDashboardMetrics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'pendingCount' : IDL.Nat,
          'inventoryItems' : IDL.Nat,
          'customersWithDebt' : IDL.Nat,
          'grossMargin' : IDL.Int,
          'lowStockCount' : IDL.Nat,
          'totalOutstandingDebt' : IDL.Int,
          'recentTransactions' : IDL.Vec(Transaction),
          'totalInflows' : IDL.Int,
          'lowStockItems' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat)),
          'totalCustomers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDraftPurchaseOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DraftPurchaseOrder), 'err' : IDL.Text })],
      ['query'],
    ),
  'getExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getFinancialSummary' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [FinancialSummary],
      ['query'],
    ),
  'getGrossMarginByPeriod' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Float64],
      ['query'],
    ),
  'getInventory' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], ['query']),
  'getInventoryByLocation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getInventoryItemNames' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getInventoryTransfers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventoryTransfer)],
      ['query'],
    ),
  'getJoinRequestStatus' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(ApprovalStatus)],
      ['query'],
    ),
  'getLocations' : IDL.Func([IDL.Text], [IDL.Vec(Location)], ['query']),
  'getLowStockAlerts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getOrGenerateScheduledSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ScheduledSummary, 'err' : IDL.Text })],
      [],
    ),
  'getOutstandingCredits' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'customersWithDebt' : IDL.Nat,
          'totalOutstanding' : IDL.Float64,
          'outstandingCredits' : IDL.Vec(
            IDL.Record({
              'balance' : IDL.Float64,
              'debtor' : IDL.Text,
              'totalOwed' : IDL.Float64,
              'amountPaid' : IDL.Float64,
              'paybackDate' : Time,
            })
          ),
        }),
      ],
      ['query'],
    ),
  'getPendingExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getPendingInventory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getPendingJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
  'getPendingTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getProductDetails' : IDL.Func([IDL.Text], [ProductDetails], ['query']),
  'getRecentTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getSettlements' : IDL.Func([IDL.Text], [IDL.Vec(Settlement)], ['query']),
  'getStockPolicy' : IDL.Func([IDL.Text], [StockPolicy], ['query']),
  'getSystemSettings' : IDL.Func([], [IDL.Opt(SystemSettings)], ['query']),
  'getTopItemsAndCustomers' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'topItems' : IDL.Vec(
            IDL.Record({
              'sku' : IDL.Text,
              'grossProfit' : IDL.Float64,
              'totalUnitsSold' : IDL.Nat,
              'brand' : IDL.Text,
            })
          ),
          'topCustomers' : IDL.Vec(
            IDL.Record({
              'name' : IDL.Text,
              'lastSaleDate' : Time,
              'totalSpent' : IDL.Float64,
            })
          ),
        }),
      ],
      ['query'],
    ),
  'getTransactionDetail' : IDL.Func([IDL.Text], [Settlement], ['query']),
  'getTransactionStatistics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'sales' : IDL.Float64,
          'creditSales' : IDL.Float64,
          'purchases' : IDL.Float64,
          'creditPurchases' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
  'getTransactionsByType' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserBooks' : IDL.Func([], [IDL.Vec(AccountingBook)], ['query']),
  'getUserDisplayName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getUserJoinRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ApprovalStatus))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoidedTransactions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Settlement)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerBookAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerBookMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerPermanentAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ApprovalStatus))],
      ['query'],
    ),
  'recordCreditPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [MutResult],
      [],
    ),
  'refundCreditPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [MutResult],
      [],
    ),
  'rejectExpense' : IDL.Func([IDL.Text], [MutResult], []),
  'rejectInventoryItem' : IDL.Func([IDL.Text], [MutResult], []),
  'rejectJoinRequest' : IDL.Func([IDL.Text], [JoinRequestResult], []),
  'rejectTransaction' : IDL.Func([IDL.Text], [MutResult], []),
  'removeSelfFromBook' : IDL.Func([IDL.Text], [JoinRequestResult], []),
  'removeUserFromBook' : IDL.Func(
      [IDL.Text, IDL.Text],
      [JoinRequestResult],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'requestJoinBook' : IDL.Func([IDL.Text], [JoinRequestResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAccountingBooks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AccountingBook)],
      ['query'],
    ),
  'searchCustomers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Customer)],
      ['query'],
    ),
  'searchInventory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setCustomerPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setProductDetails' : IDL.Func([IDL.Text, ProductDetails], [MutResult], []),
  'setStockPolicy' : IDL.Func([IDL.Text, StockPolicy], [MutResult], []),
  'transferInventory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [MutResult],
      [],
    ),
  'updateBookSettings' : IDL.Func(
      [IDL.Text, BookSettings],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCustomer' : IDL.Func([Customer], [MutResult], []),
  'updateInventoryItem' : IDL.Func([InventoryItem], [MutResult], []),
  'updateSystemSettings' : IDL.Func([SystemSettings], [], []),
  'voidTransaction' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [MutResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'bookId' : IDL.Text,
    'email' : IDL.Text,
    'outstandingDebt' : IDL.Float64,
    'totalSpent' : IDL.Float64,
    'lastTransactionDate' : Time,
    'brand' : IDL.Text,
    'phone' : IDL.Text,
    'transactions' : IDL.Vec(IDL.Text),
    'transactionCount' : IDL.Nat,
  });
  const MutResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'bookId' : IDL.Text,
    'approved' : IDL.Bool,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'supplier' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'sellingPrice' : IDL.Float64,
    'bookId' : IDL.Text,
    'variants' : IDL.Vec(IDL.Text),
    'productType' : IDL.Text,
    'highestEverQuantity' : IDL.Nat,
    'approved' : IDL.Bool,
    'locationId' : IDL.Text,
    'unitsPerCarton' : IDL.Nat,
    'quantity' : IDL.Nat,
    'brand' : IDL.Text,
    'costPrice' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'sellingPriceAtSale' : IDL.Float64,
    'costPriceAtSale' : IDL.Float64,
    'paymentMethod' : IDL.Text,
    'typeSubtype' : IDL.Text,
    'date' : Time,
    'createdBy' : IDL.Principal,
    'bookId' : IDL.Text,
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'approved' : IDL.Bool,
    'approvalProcessed' : IDL.Bool,
    'currency' : IDL.Text,
    'notes' : IDL.Text,
    'unitsPerCarton' : IDL.Nat,
    'itemName' : IDL.Text,
    'brand' : IDL.Text,
    'phone' : IDL.Text,
    'cartons' : IDL.Nat,
    'amount' : IDL.Float64,
    'pricePerCarton' : IDL.Float64,
  });
  const JoinRequestResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgingBucket = IDL.Record({
    'count' : IDL.Nat,
    'bucketLabel' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'transactions' : IDL.Vec(Transaction),
  });
  const AccountingBook = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Principal),
    'admin' : IDL.Principal,
    'adminMembers' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const JoinRequest = IDL.Record({
    'status' : ApprovalStatus,
    'user' : IDL.Principal,
    'bookId' : IDL.Text,
    'requestedAt' : Time,
  });
  const BranchComparisonItem = IDL.Record({
    'totalValue' : IDL.Float64,
    'salesVolume' : IDL.Float64,
    'totalItems' : IDL.Nat,
    'locationName' : IDL.Text,
  });
  const ApprovalTurnaround = IDL.Record({
    'fastestHours' : IDL.Float64,
    'slowestHours' : IDL.Float64,
    'avgHours' : IDL.Float64,
    'totalApproved' : IDL.Nat,
    'totalRejected' : IDL.Nat,
  });
  const ExpenseByCategoryItem = IDL.Record({
    'pct' : IDL.Float64,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const BreakEven = IDL.Record({
    'currentRevenue' : IDL.Float64,
    'surplus' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
    'requiredRevenue' : IDL.Float64,
  });
  const SalesVelocityItem = IDL.Record({
    'avgUnitsPerDay' : IDL.Float64,
    'itemName' : IDL.Text,
    'totalUnits' : IDL.Nat,
  });
  const TransactionErrorRate = IDL.Record({
    'errorRate' : IDL.Float64,
    'totalApproved' : IDL.Nat,
    'totalRejected' : IDL.Nat,
    'totalSubmitted' : IDL.Nat,
  });
  const PeakPeriod = IDL.Record({
    'period' : IDL.Text,
    'rank' : IDL.Nat,
    'volume' : IDL.Float64,
  });
  const MarginTrendPoint = IDL.Record({
    'period' : IDL.Text,
    'grossMargin' : IDL.Float64,
    'grossMarginPct' : IDL.Float64,
  });
  const ForecastPoint = IDL.Record({
    'period' : IDL.Text,
    'projected' : IDL.Float64,
  });
  const CustomerCLVItem = IDL.Record({
    'customerName' : IDL.Text,
    'firstTransactionDate' : IDL.Int,
    'totalRevenue' : IDL.Float64,
    'totalTransactions' : IDL.Nat,
  });
  const ProfitByProductItem = IDL.Record({
    'grossProfit' : IDL.Float64,
    'itemName' : IDL.Text,
    'units' : IDL.Nat,
    'margin' : IDL.Float64,
  });
  const SalesTrendPoint = IDL.Record({
    'revenue' : IDL.Float64,
    'period' : IDL.Text,
    'cost' : IDL.Float64,
    'profit' : IDL.Float64,
  });
  const UserActivityItem = IDL.Record({
    'userName' : IDL.Text,
    'actionCount' : IDL.Nat,
    'principalText' : IDL.Text,
    'lastActionDate' : IDL.Int,
  });
  const StockTurnoverItem = IDL.Record({
    'turnoverRate' : IDL.Float64,
    'timesRestocked' : IDL.Nat,
    'itemName' : IDL.Text,
  });
  const CogsItem = IDL.Record({
    'grossProfit' : IDL.Float64,
    'totalCost' : IDL.Float64,
    'itemName' : IDL.Text,
    'totalRevenue' : IDL.Float64,
  });
  const RepeatVsNewItem = IDL.Record({
    'repeatCount' : IDL.Nat,
    'repeatPct' : IDL.Float64,
    'period' : IDL.Text,
    'newCount' : IDL.Nat,
  });
  const DeadStockItem = IDL.Record({
    'itemName' : IDL.Text,
    'daysSinceLastSale' : IDL.Nat,
    'currentQty' : IDL.Nat,
  });
  const TopCustomerByProfit = IDL.Record({
    'customerName' : IDL.Text,
    'grossProfit' : IDL.Float64,
    'totalRevenue' : IDL.Float64,
  });
  const AnalyticsExtended = IDL.Record({
    'branchComparison' : IDL.Vec(BranchComparisonItem),
    'approvalTurnaround' : ApprovalTurnaround,
    'expenseByCategory' : IDL.Vec(ExpenseByCategoryItem),
    'breakEven' : BreakEven,
    'salesVelocity' : IDL.Vec(SalesVelocityItem),
    'transactionErrorRate' : TransactionErrorRate,
    'peakPeriods' : IDL.Vec(PeakPeriod),
    'marginTrend' : IDL.Vec(MarginTrendPoint),
    'revenueForecast' : IDL.Vec(ForecastPoint),
    'customerCLV' : IDL.Vec(CustomerCLVItem),
    'profitByProduct' : IDL.Vec(ProfitByProductItem),
    'salesTrend' : IDL.Vec(SalesTrendPoint),
    'userActivity' : IDL.Vec(UserActivityItem),
    'stockTurnover' : IDL.Vec(StockTurnoverItem),
    'cogsBreakdown' : IDL.Vec(CogsItem),
    'repeatVsNewRatio' : IDL.Vec(RepeatVsNewItem),
    'deadStock' : IDL.Vec(DeadStockItem),
    'topCustomersByProfit' : IDL.Vec(TopCustomerByProfit),
    'debtAging' : IDL.Vec(AgingBucket),
  });
  const AuditLogEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'actorName' : IDL.Text,
    'bookId' : IDL.Text,
    'timestamp' : IDL.Int,
    'targetType' : IDL.Text,
    'details' : IDL.Text,
    'actorPrincipal' : IDL.Text,
    'targetId' : IDL.Text,
  });
  const BookSettings = IDL.Record({
    'hideCostPricesFromNonAdmins' : IDL.Bool,
    'baseCurrency' : IDL.Text,
    'scheduledSummaryFrequency' : IDL.Text,
    'bookId' : IDL.Text,
    'exchangeRate' : IDL.Float64,
    'lastSummaryDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CustomerStatement = IDL.Record({
    'customerName' : IDL.Text,
    'currentBalance' : IDL.Float64,
    'totalPayments' : IDL.Float64,
    'totalPurchases' : IDL.Float64,
    'transactions' : IDL.Vec(Transaction),
  });
  const DraftPurchaseOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'inventoryItemId' : IDL.Text,
    'suggestedQuantity' : IDL.Nat,
    'bookId' : IDL.Text,
    'currentQuantity' : IDL.Nat,
    'triggeredAt' : IDL.Int,
    'itemName' : IDL.Text,
  });
  const FinancialSummary = IDL.Record({
    'grossProfit' : IDL.Float64,
    'expenses' : IDL.Float64,
    'marginPercent' : IDL.Float64,
    'receipts' : IDL.Float64,
    'netProfit' : IDL.Float64,
  });
  const InventoryTransfer = IDL.Record({
    'id' : IDL.Text,
    'itemId' : IDL.Text,
    'toLocationId' : IDL.Text,
    'unit' : IDL.Text,
    'bookId' : IDL.Text,
    'fromLocationId' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'transferredAt' : Time,
    'transferredBy' : IDL.Principal,
  });
  const Location = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'bookId' : IDL.Text,
  });
  const ScheduledSummary = IDL.Record({
    'id' : IDL.Text,
    'topItemNames' : IDL.Vec(IDL.Text),
    'grossMargin' : IDL.Float64,
    'generatedAt' : IDL.Int,
    'topCustomerNames' : IDL.Vec(IDL.Text),
    'bookId' : IDL.Text,
    'totalExpenses' : IDL.Float64,
    'periodLabel' : IDL.Text,
    'totalInflows' : IDL.Float64,
    'transactionCount' : IDL.Nat,
  });
  const ProductDetails = IDL.Record({
    'description' : IDL.Text,
    'image' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'method' : IDL.Text,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'recordedBy' : IDL.Principal,
    'amount' : IDL.Float64,
    'transactionId' : IDL.Text,
  });
  const Revision = IDL.Record({
    'action' : IDL.Text,
    'actorName' : IDL.Text,
    'after' : Transaction,
    'before' : Transaction,
    'timestamp' : IDL.Int,
    'actorPrincipal' : IDL.Principal,
    'revision' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const Settlement = IDL.Record({
    'balance' : IDL.Float64,
    'payments' : IDL.Vec(Payment),
    'paid' : IDL.Float64,
    'transaction' : Transaction,
    'voided' : IDL.Bool,
    'history' : IDL.Vec(Revision),
    'refundDue' : IDL.Float64,
    'profit' : IDL.Float64,
    'revision' : IDL.Nat,
  });
  const StockPolicy = IDL.Record({
    'leadDays' : IDL.Nat,
    'minimumUnits' : IDL.Nat,
    'targetUnits' : IDL.Nat,
    'enabled' : IDL.Bool,
  });
  const SystemSettings = IDL.Record({
    'multiStore' : IDL.Bool,
    'exchangeRate' : IDL.Float64,
    'companyInfo' : IDL.Text,
    'taxRate' : IDL.Float64,
    'currencyRounding' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([Customer], [MutResult], []),
    'addExpense' : IDL.Func([Expense], [MutResult], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [MutResult], []),
    'addTransaction' : IDL.Func([Transaction], [MutResult], []),
    'amendExpense' : IDL.Func(
        [Expense, IDL.Float64, IDL.Text, IDL.Bool],
        [MutResult],
        [],
      ),
    'amendTransaction' : IDL.Func(
        [Transaction, IDL.Nat, IDL.Text],
        [MutResult],
        [],
      ),
    'approveExpense' : IDL.Func([IDL.Text], [MutResult], []),
    'approveInventoryItem' : IDL.Func([IDL.Text], [MutResult], []),
    'approveJoinRequest' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [JoinRequestResult],
        [],
      ),
    'approveTransaction' : IDL.Func([IDL.Text], [MutResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeUserRole' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [JoinRequestResult],
        [],
      ),
    'createAccountingBook' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createLocation' : IDL.Func([IDL.Text, IDL.Text], [MutResult], []),
    'deleteBook' : IDL.Func([IDL.Text], [JoinRequestResult], []),
    'deleteLocation' : IDL.Func([IDL.Text, IDL.Text], [MutResult], []),
    'deleteTransaction' : IDL.Func([IDL.Text], [MutResult], []),
    'dismissDraftPurchaseOrder' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAgingReport' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(AgingBucket), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAllBooks' : IDL.Func([], [IDL.Vec(AccountingBook)], ['query']),
    'getAllJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
    'getAnalyticsExtended' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AnalyticsExtended, 'err' : IDL.Text })],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(AuditLogEntry), 'err' : IDL.Text })],
        ['query'],
      ),
    'getBookMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getBookMembersWithNames' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getBookSettings' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : BookSettings, 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerNames' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getCustomerPhoto' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], ['query']),
    'getCustomerStatement' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : CustomerStatement, 'err' : IDL.Text })],
        ['query'],
      ),
    'getCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'getDashboardMetrics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'pendingCount' : IDL.Nat,
            'inventoryItems' : IDL.Nat,
            'customersWithDebt' : IDL.Nat,
            'grossMargin' : IDL.Int,
            'lowStockCount' : IDL.Nat,
            'totalOutstandingDebt' : IDL.Int,
            'recentTransactions' : IDL.Vec(Transaction),
            'totalInflows' : IDL.Int,
            'lowStockItems' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat)),
            'totalCustomers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDraftPurchaseOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(DraftPurchaseOrder), 'err' : IDL.Text })],
        ['query'],
      ),
    'getExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getFinancialSummary' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [FinancialSummary],
        ['query'],
      ),
    'getGrossMarginByPeriod' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Float64],
        ['query'],
      ),
    'getInventory' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], ['query']),
    'getInventoryByLocation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getInventoryItemNames' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getInventoryTransfers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventoryTransfer)],
        ['query'],
      ),
    'getJoinRequestStatus' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(ApprovalStatus)],
        ['query'],
      ),
    'getLocations' : IDL.Func([IDL.Text], [IDL.Vec(Location)], ['query']),
    'getLowStockAlerts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getOrGenerateScheduledSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ScheduledSummary, 'err' : IDL.Text })],
        [],
      ),
    'getOutstandingCredits' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'customersWithDebt' : IDL.Nat,
            'totalOutstanding' : IDL.Float64,
            'outstandingCredits' : IDL.Vec(
              IDL.Record({
                'balance' : IDL.Float64,
                'debtor' : IDL.Text,
                'totalOwed' : IDL.Float64,
                'amountPaid' : IDL.Float64,
                'paybackDate' : Time,
              })
            ),
          }),
        ],
        ['query'],
      ),
    'getPendingExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getPendingInventory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getPendingJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
    'getPendingTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getProductDetails' : IDL.Func([IDL.Text], [ProductDetails], ['query']),
    'getRecentTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getSettlements' : IDL.Func([IDL.Text], [IDL.Vec(Settlement)], ['query']),
    'getStockPolicy' : IDL.Func([IDL.Text], [StockPolicy], ['query']),
    'getSystemSettings' : IDL.Func([], [IDL.Opt(SystemSettings)], ['query']),
    'getTopItemsAndCustomers' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'topItems' : IDL.Vec(
              IDL.Record({
                'sku' : IDL.Text,
                'grossProfit' : IDL.Float64,
                'totalUnitsSold' : IDL.Nat,
                'brand' : IDL.Text,
              })
            ),
            'topCustomers' : IDL.Vec(
              IDL.Record({
                'name' : IDL.Text,
                'lastSaleDate' : Time,
                'totalSpent' : IDL.Float64,
              })
            ),
          }),
        ],
        ['query'],
      ),
    'getTransactionDetail' : IDL.Func([IDL.Text], [Settlement], ['query']),
    'getTransactionStatistics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'sales' : IDL.Float64,
            'creditSales' : IDL.Float64,
            'purchases' : IDL.Float64,
            'creditPurchases' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getTransactions' : IDL.Func([IDL.Text], [IDL.Vec(Transaction)], ['query']),
    'getTransactionsByType' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserBooks' : IDL.Func([], [IDL.Vec(AccountingBook)], ['query']),
    'getUserDisplayName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getUserJoinRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ApprovalStatus))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoidedTransactions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Settlement)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerBookAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerBookMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerPermanentAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ApprovalStatus))],
        ['query'],
      ),
    'recordCreditPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [MutResult],
        [],
      ),
    'refundCreditPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [MutResult],
        [],
      ),
    'rejectExpense' : IDL.Func([IDL.Text], [MutResult], []),
    'rejectInventoryItem' : IDL.Func([IDL.Text], [MutResult], []),
    'rejectJoinRequest' : IDL.Func([IDL.Text], [JoinRequestResult], []),
    'rejectTransaction' : IDL.Func([IDL.Text], [MutResult], []),
    'removeSelfFromBook' : IDL.Func([IDL.Text], [JoinRequestResult], []),
    'removeUserFromBook' : IDL.Func(
        [IDL.Text, IDL.Text],
        [JoinRequestResult],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'requestJoinBook' : IDL.Func([IDL.Text], [JoinRequestResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAccountingBooks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AccountingBook)],
        ['query'],
      ),
    'searchCustomers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    'searchInventory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setCustomerPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setProductDetails' : IDL.Func([IDL.Text, ProductDetails], [MutResult], []),
    'setStockPolicy' : IDL.Func([IDL.Text, StockPolicy], [MutResult], []),
    'transferInventory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [MutResult],
        [],
      ),
    'updateBookSettings' : IDL.Func(
        [IDL.Text, BookSettings],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCustomer' : IDL.Func([Customer], [MutResult], []),
    'updateInventoryItem' : IDL.Func([InventoryItem], [MutResult], []),
    'updateSystemSettings' : IDL.Func([SystemSettings], [], []),
    'voidTransaction' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [MutResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };