/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountingBook {
  'id' : string,
  'members' : Array<Principal>,
  'admin' : Principal,
  'adminMembers' : Array<Principal>,
  'name' : string,
  'createdAt' : Time,
}
export interface AgingBucket {
  'count' : bigint,
  'bucketLabel' : string,
  'totalAmount' : number,
  'transactions' : Array<Transaction>,
}
export interface AnalyticsExtended {
  'branchComparison' : Array<BranchComparisonItem>,
  'approvalTurnaround' : ApprovalTurnaround,
  'expenseByCategory' : Array<ExpenseByCategoryItem>,
  'breakEven' : BreakEven,
  'salesVelocity' : Array<SalesVelocityItem>,
  'transactionErrorRate' : TransactionErrorRate,
  'peakPeriods' : Array<PeakPeriod>,
  'marginTrend' : Array<MarginTrendPoint>,
  'revenueForecast' : Array<ForecastPoint>,
  'customerCLV' : Array<CustomerCLVItem>,
  'profitByProduct' : Array<ProfitByProductItem>,
  'salesTrend' : Array<SalesTrendPoint>,
  'userActivity' : Array<UserActivityItem>,
  'stockTurnover' : Array<StockTurnoverItem>,
  'cogsBreakdown' : Array<CogsItem>,
  'repeatVsNewRatio' : Array<RepeatVsNewItem>,
  'deadStock' : Array<DeadStockItem>,
  'topCustomersByProfit' : Array<TopCustomerByProfit>,
  'debtAging' : Array<AgingBucket>,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ApprovalTurnaround {
  'fastestHours' : number,
  'slowestHours' : number,
  'avgHours' : number,
  'totalApproved' : bigint,
  'totalRejected' : bigint,
}
export interface AuditLogEntry {
  'id' : string,
  'action' : string,
  'actorName' : string,
  'bookId' : string,
  'timestamp' : bigint,
  'targetType' : string,
  'details' : string,
  'actorPrincipal' : string,
  'targetId' : string,
}
export interface BookSettings {
  'hideCostPricesFromNonAdmins' : boolean,
  'baseCurrency' : string,
  'scheduledSummaryFrequency' : string,
  'bookId' : string,
  'exchangeRate' : number,
  'lastSummaryDate' : bigint,
}
export interface BranchComparisonItem {
  'totalValue' : number,
  'salesVolume' : number,
  'totalItems' : bigint,
  'locationName' : string,
}
export interface BreakEven {
  'currentRevenue' : number,
  'surplus' : number,
  'totalExpenses' : number,
  'requiredRevenue' : number,
}
export interface CogsItem {
  'grossProfit' : number,
  'totalCost' : number,
  'itemName' : string,
  'totalRevenue' : number,
}
export interface Customer {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'bookId' : string,
  'email' : string,
  'outstandingDebt' : number,
  'totalSpent' : number,
  'lastTransactionDate' : Time,
  'brand' : string,
  'phone' : string,
  'transactions' : Array<string>,
  'transactionCount' : bigint,
}
export interface CustomerCLVItem {
  'customerName' : string,
  'firstTransactionDate' : bigint,
  'totalRevenue' : number,
  'totalTransactions' : bigint,
}
export interface CustomerStatement {
  'customerName' : string,
  'currentBalance' : number,
  'totalPayments' : number,
  'totalPurchases' : number,
  'transactions' : Array<Transaction>,
}
export interface DeadStockItem {
  'itemName' : string,
  'daysSinceLastSale' : bigint,
  'currentQty' : bigint,
}
export interface DraftPurchaseOrder {
  'id' : string,
  'status' : string,
  'inventoryItemId' : string,
  'suggestedQuantity' : bigint,
  'bookId' : string,
  'currentQuantity' : bigint,
  'triggeredAt' : bigint,
  'itemName' : string,
}
export interface Expense {
  'id' : string,
  'date' : Time,
  'createdBy' : Principal,
  'description' : string,
  'bookId' : string,
  'approved' : boolean,
  'category' : string,
  'amount' : number,
}
export interface ExpenseByCategoryItem {
  'pct' : number,
  'category' : string,
  'amount' : number,
}
export interface ForecastPoint { 'period' : string, 'projected' : number }
export interface InventoryItem {
  'id' : string,
  'supplier' : string,
  'name' : string,
  'createdAt' : Time,
  'sellingPrice' : number,
  'bookId' : string,
  'variants' : Array<string>,
  'productType' : string,
  'highestEverQuantity' : bigint,
  'approved' : boolean,
  'locationId' : string,
  'unitsPerCarton' : bigint,
  'quantity' : bigint,
  'brand' : string,
  'costPrice' : number,
}
export interface InventoryTransfer {
  'id' : string,
  'itemId' : string,
  'toLocationId' : string,
  'unit' : string,
  'bookId' : string,
  'fromLocationId' : string,
  'itemName' : string,
  'quantity' : bigint,
  'transferredAt' : Time,
  'transferredBy' : Principal,
}
export interface JoinRequest {
  'status' : ApprovalStatus,
  'user' : Principal,
  'bookId' : string,
  'requestedAt' : Time,
}
export type JoinRequestResult = { 'ok' : string } |
  { 'err' : string };
export interface Location {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'bookId' : string,
}
export interface MarginTrendPoint {
  'period' : string,
  'grossMargin' : number,
  'grossMarginPct' : number,
}
export type MutResult = { 'ok' : string } |
  { 'err' : string };
export interface PeakPeriod {
  'period' : string,
  'rank' : bigint,
  'volume' : number,
}
export interface ProfitByProductItem {
  'grossProfit' : number,
  'itemName' : string,
  'units' : bigint,
  'margin' : number,
}
export interface RepeatVsNewItem {
  'repeatCount' : bigint,
  'repeatPct' : number,
  'period' : string,
  'newCount' : bigint,
}
export interface SalesTrendPoint {
  'revenue' : number,
  'period' : string,
  'cost' : number,
  'profit' : number,
}
export interface SalesVelocityItem {
  'avgUnitsPerDay' : number,
  'itemName' : string,
  'totalUnits' : bigint,
}
export interface ScheduledSummary {
  'id' : string,
  'topItemNames' : Array<string>,
  'grossMargin' : number,
  'generatedAt' : bigint,
  'topCustomerNames' : Array<string>,
  'bookId' : string,
  'totalExpenses' : number,
  'periodLabel' : string,
  'totalInflows' : number,
  'transactionCount' : bigint,
}
export interface StockTurnoverItem {
  'turnoverRate' : number,
  'timesRestocked' : bigint,
  'itemName' : string,
}
export interface SystemSettings {
  'multiStore' : boolean,
  'exchangeRate' : number,
  'companyInfo' : string,
  'taxRate' : number,
  'currencyRounding' : bigint,
}
export type Time = bigint;
export interface TopCustomerByProfit {
  'customerName' : string,
  'grossProfit' : number,
  'totalRevenue' : number,
}
export interface Transaction {
  'id' : string,
  'customerName' : string,
  'sellingPriceAtSale' : number,
  'costPriceAtSale' : number,
  'paymentMethod' : string,
  'typeSubtype' : string,
  'date' : Time,
  'createdBy' : Principal,
  'bookId' : string,
  'productType' : string,
  'email' : string,
  'approved' : boolean,
  'approvalProcessed' : boolean,
  'currency' : string,
  'notes' : string,
  'unitsPerCarton' : bigint,
  'itemName' : string,
  'brand' : string,
  'phone' : string,
  'cartons' : bigint,
  'amount' : number,
  'pricePerCarton' : number,
}
export interface TransactionErrorRate {
  'errorRate' : number,
  'totalApproved' : bigint,
  'totalRejected' : bigint,
  'totalSubmitted' : bigint,
}
export interface UserActivityItem {
  'userName' : string,
  'actionCount' : bigint,
  'principalText' : string,
  'lastActionDate' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addCustomer' : ActorMethod<[Customer], MutResult>,
  'addExpense' : ActorMethod<[Expense], MutResult>,
  'addInventoryItem' : ActorMethod<[InventoryItem], MutResult>,
  'addTransaction' : ActorMethod<[Transaction], MutResult>,
  'approveExpense' : ActorMethod<[string], MutResult>,
  'approveInventoryItem' : ActorMethod<[string], MutResult>,
  'approveJoinRequest' : ActorMethod<[string, boolean], JoinRequestResult>,
  'approveTransaction' : ActorMethod<[string], MutResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeUserRole' : ActorMethod<[string, string, boolean], JoinRequestResult>,
  'createAccountingBook' : ActorMethod<[string], string>,
  'createLocation' : ActorMethod<[string, string], MutResult>,
  'deleteBook' : ActorMethod<[string], JoinRequestResult>,
  'deleteLocation' : ActorMethod<[string, string], MutResult>,
  'deleteTransaction' : ActorMethod<[string], MutResult>,
  'dismissDraftPurchaseOrder' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAgingReport' : ActorMethod<
    [string],
    { 'ok' : Array<AgingBucket> } |
      { 'err' : string }
  >,
  'getAllBooks' : ActorMethod<[], Array<AccountingBook>>,
  'getAllJoinRequests' : ActorMethod<[], Array<JoinRequest>>,
  'getAnalyticsExtended' : ActorMethod<
    [string, string],
    { 'ok' : AnalyticsExtended } |
      { 'err' : string }
  >,
  'getAuditLog' : ActorMethod<
    [string],
    { 'ok' : Array<AuditLogEntry> } |
      { 'err' : string }
  >,
  'getBookMembers' : ActorMethod<[string], Array<Principal>>,
  'getBookMembersWithNames' : ActorMethod<
    [string],
    Array<[Principal, string, boolean]>
  >,
  'getBookSettings' : ActorMethod<
    [string],
    { 'ok' : BookSettings } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerNames' : ActorMethod<[string], Array<string>>,
  'getCustomerStatement' : ActorMethod<
    [string, string],
    { 'ok' : CustomerStatement } |
      { 'err' : string }
  >,
  'getCustomers' : ActorMethod<[string], Array<Customer>>,
  'getDashboardMetrics' : ActorMethod<
    [string],
    {
      'pendingCount' : bigint,
      'inventoryItems' : bigint,
      'customersWithDebt' : bigint,
      'grossMargin' : bigint,
      'lowStockCount' : bigint,
      'totalOutstandingDebt' : bigint,
      'recentTransactions' : Array<Transaction>,
      'totalInflows' : bigint,
      'lowStockItems' : Array<[string, bigint, bigint]>,
      'totalCustomers' : bigint,
    }
  >,
  'getDraftPurchaseOrders' : ActorMethod<
    [string],
    { 'ok' : Array<DraftPurchaseOrder> } |
      { 'err' : string }
  >,
  'getExpenses' : ActorMethod<[string], Array<Expense>>,
  'getGrossMarginByPeriod' : ActorMethod<[string, bigint, bigint], number>,
  'getInventory' : ActorMethod<[string], Array<InventoryItem>>,
  'getInventoryByLocation' : ActorMethod<
    [string, string],
    Array<InventoryItem>
  >,
  'getInventoryItemNames' : ActorMethod<[string], Array<string>>,
  'getInventoryTransfers' : ActorMethod<[string], Array<InventoryTransfer>>,
  'getJoinRequestStatus' : ActorMethod<
    [Principal, string],
    [] | [ApprovalStatus]
  >,
  'getLocations' : ActorMethod<[string], Array<Location>>,
  'getLowStockAlerts' : ActorMethod<[string], Array<InventoryItem>>,
  'getOrGenerateScheduledSummary' : ActorMethod<
    [string],
    { 'ok' : ScheduledSummary } |
      { 'err' : string }
  >,
  'getOutstandingCredits' : ActorMethod<
    [string],
    {
      'customersWithDebt' : bigint,
      'totalOutstanding' : number,
      'outstandingCredits' : Array<
        {
          'balance' : number,
          'debtor' : string,
          'totalOwed' : number,
          'amountPaid' : number,
          'paybackDate' : Time,
        }
      >,
    }
  >,
  'getPendingExpenses' : ActorMethod<[string], Array<Expense>>,
  'getPendingInventory' : ActorMethod<[string], Array<InventoryItem>>,
  'getPendingJoinRequests' : ActorMethod<[], Array<JoinRequest>>,
  'getPendingTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getRecentTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getSystemSettings' : ActorMethod<[], [] | [SystemSettings]>,
  'getTopItemsAndCustomers' : ActorMethod<
    [string],
    {
      'topItems' : Array<
        {
          'sku' : string,
          'grossProfit' : number,
          'totalUnitsSold' : bigint,
          'brand' : string,
        }
      >,
      'topCustomers' : Array<
        { 'name' : string, 'lastSaleDate' : Time, 'totalSpent' : number }
      >,
    }
  >,
  'getTransactionStatistics' : ActorMethod<
    [string],
    {
      'sales' : number,
      'creditSales' : number,
      'purchases' : number,
      'creditPurchases' : number,
    }
  >,
  'getTransactions' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsByType' : ActorMethod<[string, string], Array<Transaction>>,
  'getUserBooks' : ActorMethod<[], Array<AccountingBook>>,
  'getUserDisplayName' : ActorMethod<[Principal], string>,
  'getUserJoinRequests' : ActorMethod<[], Array<[string, ApprovalStatus]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerBookAdmin' : ActorMethod<[string], boolean>,
  'isCallerBookMember' : ActorMethod<[string], boolean>,
  'isCallerPermanentAdmin' : ActorMethod<[string], boolean>,
  'listApprovals' : ActorMethod<[], Array<[Principal, ApprovalStatus]>>,
  'rejectExpense' : ActorMethod<[string], MutResult>,
  'rejectInventoryItem' : ActorMethod<[string], MutResult>,
  'rejectJoinRequest' : ActorMethod<[string], JoinRequestResult>,
  'rejectTransaction' : ActorMethod<[string], MutResult>,
  'removeSelfFromBook' : ActorMethod<[string], JoinRequestResult>,
  'removeUserFromBook' : ActorMethod<[string, string], JoinRequestResult>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestJoinBook' : ActorMethod<[string], JoinRequestResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAccountingBooks' : ActorMethod<[string], Array<AccountingBook>>,
  'searchCustomers' : ActorMethod<[string, string], Array<Customer>>,
  'searchInventory' : ActorMethod<[string, string], Array<InventoryItem>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'transferInventory' : ActorMethod<
    [string, string, string, string, bigint, string],
    MutResult
  >,
  'updateBookSettings' : ActorMethod<
    [string, BookSettings],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCustomer' : ActorMethod<[Customer], MutResult>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], MutResult>,
  'updateSystemSettings' : ActorMethod<[SystemSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];