/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    id: string;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    bookId: string;
}
export interface UserProfile {
    name: string;
    email: string;
    company: string;
    phone: string;
}
export interface AccountingBook {
    id: string;
    members: Array<Principal>;
    admin: Principal;
    adminMembers: Array<Principal>;
    name: string;
    createdAt: Time;
}
export type Time = bigint;
export interface TransactionErrorRate {
    errorRate: number;
    totalApproved: bigint;
    totalRejected: bigint;
    totalSubmitted: bigint;
}
export interface CustomerCLVItem {
    customerName: string;
    firstTransactionDate: bigint;
    totalRevenue: number;
    totalTransactions: bigint;
}
export interface CogsItem {
    grossProfit: number;
    totalCost: number;
    itemName: string;
    totalRevenue: number;
}
export interface AgingBucket {
    count: bigint;
    bucketLabel: string;
    totalAmount: number;
    transactions: Array<Transaction>;
}
export interface CustomerStatement {
    customerName: string;
    currentBalance: number;
    totalPayments: number;
    totalPurchases: number;
    transactions: Array<Transaction>;
}
export interface Transaction {
    id: string;
    customerName: string;
    sellingPriceAtSale: number;
    costPriceAtSale: number;
    paymentMethod: string;
    typeSubtype: string;
    date: Time;
    createdBy: Principal;
    bookId: string;
    productType: string;
    email: string;
    approved: boolean;
    approvalProcessed: boolean;
    currency: string;
    notes: string;
    unitsPerCarton: bigint;
    itemName: string;
    brand: string;
    phone: string;
    cartons: bigint;
    amount: number;
    pricePerCarton: number;
}
export interface InventoryItem {
    id: string;
    supplier: string;
    name: string;
    createdAt: Time;
    sellingPrice: number;
    bookId: string;
    variants: Array<string>;
    productType: string;
    highestEverQuantity: bigint;
    approved: boolean;
    locationId: string;
    unitsPerCarton: bigint;
    quantity: bigint;
    brand: string;
    costPrice: number;
}
export interface BookSettings {
    hideCostPricesFromNonAdmins: boolean;
    baseCurrency: string;
    scheduledSummaryFrequency: string;
    bookId: string;
    exchangeRate: number;
    lastSummaryDate: bigint;
}
export interface SystemSettings {
    multiStore: boolean;
    exchangeRate: number;
    companyInfo: string;
    taxRate: number;
    currencyRounding: bigint;
}
export interface ProfitByProductItem {
    grossProfit: number;
    itemName: string;
    units: bigint;
    margin: number;
}
export interface MarginTrendPoint {
    period: string;
    grossMargin: number;
    grossMarginPct: number;
}
export interface UserActivityItem {
    userName: string;
    actionCount: bigint;
    principalText: string;
    lastActionDate: bigint;
}
export type JoinRequestResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface AnalyticsExtended {
    branchComparison: Array<BranchComparisonItem>;
    approvalTurnaround: ApprovalTurnaround;
    expenseByCategory: Array<ExpenseByCategoryItem>;
    breakEven: BreakEven;
    salesVelocity: Array<SalesVelocityItem>;
    transactionErrorRate: TransactionErrorRate;
    peakPeriods: Array<PeakPeriod>;
    marginTrend: Array<MarginTrendPoint>;
    revenueForecast: Array<ForecastPoint>;
    customerCLV: Array<CustomerCLVItem>;
    profitByProduct: Array<ProfitByProductItem>;
    salesTrend: Array<SalesTrendPoint>;
    userActivity: Array<UserActivityItem>;
    stockTurnover: Array<StockTurnoverItem>;
    cogsBreakdown: Array<CogsItem>;
    repeatVsNewRatio: Array<RepeatVsNewItem>;
    deadStock: Array<DeadStockItem>;
    topCustomersByProfit: Array<TopCustomerByProfit>;
    debtAging: Array<AgingBucket>;
}
export interface TopCustomerByProfit {
    customerName: string;
    grossProfit: number;
    totalRevenue: number;
}
export interface RepeatVsNewItem {
    repeatCount: bigint;
    repeatPct: number;
    period: string;
    newCount: bigint;
}
export interface BreakEven {
    currentRevenue: number;
    surplus: number;
    totalExpenses: number;
    requiredRevenue: number;
}
export interface ForecastPoint {
    period: string;
    projected: number;
}
export interface ExpenseByCategoryItem {
    pct: number;
    category: string;
    amount: number;
}
export interface AuditLogEntry {
    id: string;
    action: string;
    actorName: string;
    bookId: string;
    timestamp: bigint;
    targetType: string;
    details: string;
    actorPrincipal: string;
    targetId: string;
}
export interface Expense {
    id: string;
    date: Time;
    createdBy: Principal;
    description: string;
    bookId: string;
    approved: boolean;
    category: string;
    amount: number;
}
export interface Customer {
    id: string;
    name: string;
    createdAt: Time;
    bookId: string;
    email: string;
    outstandingDebt: number;
    totalSpent: number;
    lastTransactionDate: Time;
    brand: string;
    phone: string;
    transactions: Array<string>;
    transactionCount: bigint;
}
export interface ApprovalTurnaround {
    fastestHours: number;
    slowestHours: number;
    avgHours: number;
    totalApproved: bigint;
    totalRejected: bigint;
}
export interface SalesVelocityItem {
    avgUnitsPerDay: number;
    itemName: string;
    totalUnits: bigint;
}
export interface DeadStockItem {
    itemName: string;
    daysSinceLastSale: bigint;
    currentQty: bigint;
}
export interface ScheduledSummary {
    id: string;
    topItemNames: Array<string>;
    grossMargin: number;
    generatedAt: bigint;
    topCustomerNames: Array<string>;
    bookId: string;
    totalExpenses: number;
    periodLabel: string;
    totalInflows: number;
    transactionCount: bigint;
}
export type MutResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface DraftPurchaseOrder {
    id: string;
    status: string;
    inventoryItemId: string;
    suggestedQuantity: bigint;
    bookId: string;
    currentQuantity: bigint;
    triggeredAt: bigint;
    itemName: string;
}
export interface BranchComparisonItem {
    totalValue: number;
    salesVolume: number;
    totalItems: bigint;
    locationName: string;
}
export interface InventoryTransfer {
    id: string;
    itemId: string;
    toLocationId: string;
    unit: string;
    bookId: string;
    fromLocationId: string;
    itemName: string;
    quantity: bigint;
    transferredAt: Time;
    transferredBy: Principal;
}
export interface SalesTrendPoint {
    revenue: number;
    period: string;
    cost: number;
    profit: number;
}
export interface StockTurnoverItem {
    turnoverRate: number;
    timesRestocked: bigint;
    itemName: string;
}
export interface PeakPeriod {
    period: string;
    rank: bigint;
    volume: number;
}
export interface JoinRequest {
    status: ApprovalStatus;
    user: Principal;
    bookId: string;
    requestedAt: Time;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addCustomer(customer: Customer): Promise<MutResult>;
    addExpense(expense: Expense): Promise<MutResult>;
    addInventoryItem(item: InventoryItem): Promise<MutResult>;
    addTransaction(transaction: Transaction): Promise<MutResult>;
    approveExpense(expenseId: string): Promise<MutResult>;
    approveInventoryItem(itemId: string): Promise<MutResult>;
    approveJoinRequest(requestId: string, makeAdmin: boolean): Promise<JoinRequestResult>;
    approveTransaction(transactionId: string): Promise<MutResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeUserRole(bookId: string, principalText: string, makeAdmin: boolean): Promise<JoinRequestResult>;
    createAccountingBook(name: string): Promise<string>;
    createLocation(bookId: string, name: string): Promise<MutResult>;
    deleteBook(bookId: string): Promise<JoinRequestResult>;
    deleteLocation(bookId: string, locationId: string): Promise<MutResult>;
    deleteTransaction(transactionId: string): Promise<MutResult>;
    dismissDraftPurchaseOrder(bookId: string, orderId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAgingReport(bookId: string): Promise<{
        __kind__: "ok";
        ok: Array<AgingBucket>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllBooks(): Promise<Array<AccountingBook>>;
    getAllJoinRequests(): Promise<Array<JoinRequest>>;
    getAnalyticsExtended(bookId: string, timeFilter: string): Promise<{
        __kind__: "ok";
        ok: AnalyticsExtended;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAuditLog(bookId: string): Promise<{
        __kind__: "ok";
        ok: Array<AuditLogEntry>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getBookMembers(bookId: string): Promise<Array<Principal>>;
    getBookMembersWithNames(bookId: string): Promise<Array<[Principal, string, boolean]>>;
    getBookSettings(bookId: string): Promise<{
        __kind__: "ok";
        ok: BookSettings;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerNames(bookId: string): Promise<Array<string>>;
    getCustomerStatement(bookId: string, customerName: string): Promise<{
        __kind__: "ok";
        ok: CustomerStatement;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCustomers(bookId: string): Promise<Array<Customer>>;
    getDashboardMetrics(bookId: string): Promise<{
        pendingCount: bigint;
        inventoryItems: bigint;
        customersWithDebt: bigint;
        grossMargin: bigint;
        lowStockCount: bigint;
        totalOutstandingDebt: bigint;
        recentTransactions: Array<Transaction>;
        totalInflows: bigint;
        lowStockItems: Array<[string, bigint, bigint]>;
        totalCustomers: bigint;
    }>;
    getDraftPurchaseOrders(bookId: string): Promise<{
        __kind__: "ok";
        ok: Array<DraftPurchaseOrder>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getExpenses(bookId: string): Promise<Array<Expense>>;
    getGrossMarginByPeriod(bookId: string, startTime: bigint, endTime: bigint): Promise<number>;
    getInventory(bookId: string): Promise<Array<InventoryItem>>;
    getInventoryByLocation(bookId: string, locationId: string): Promise<Array<InventoryItem>>;
    getInventoryItemNames(bookId: string): Promise<Array<string>>;
    getInventoryTransfers(bookId: string): Promise<Array<InventoryTransfer>>;
    getJoinRequestStatus(user: Principal, bookId: string): Promise<ApprovalStatus | null>;
    getLocations(bookId: string): Promise<Array<Location>>;
    getLowStockAlerts(bookId: string): Promise<Array<InventoryItem>>;
    getOrGenerateScheduledSummary(bookId: string): Promise<{
        __kind__: "ok";
        ok: ScheduledSummary;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getOutstandingCredits(bookId: string): Promise<{
        customersWithDebt: bigint;
        totalOutstanding: number;
        outstandingCredits: Array<{
            balance: number;
            debtor: string;
            totalOwed: number;
            amountPaid: number;
            paybackDate: Time;
        }>;
    }>;
    getPendingExpenses(bookId: string): Promise<Array<Expense>>;
    getPendingInventory(bookId: string): Promise<Array<InventoryItem>>;
    getPendingJoinRequests(): Promise<Array<JoinRequest>>;
    getPendingTransactions(bookId: string): Promise<Array<Transaction>>;
    getRecentTransactions(bookId: string): Promise<Array<Transaction>>;
    getSystemSettings(): Promise<SystemSettings | null>;
    getTopItemsAndCustomers(bookId: string): Promise<{
        topItems: Array<{
            sku: string;
            grossProfit: number;
            totalUnitsSold: bigint;
            brand: string;
        }>;
        topCustomers: Array<{
            name: string;
            lastSaleDate: Time;
            totalSpent: number;
        }>;
    }>;
    getTransactionStatistics(bookId: string): Promise<{
        sales: number;
        creditSales: number;
        purchases: number;
        creditPurchases: number;
    }>;
    getTransactions(bookId: string): Promise<Array<Transaction>>;
    getTransactionsByType(bookId: string, transactionType: string): Promise<Array<Transaction>>;
    getUserBooks(): Promise<Array<AccountingBook>>;
    getUserDisplayName(user: Principal): Promise<string>;
    getUserJoinRequests(): Promise<Array<[string, ApprovalStatus]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isCallerBookAdmin(bookId: string): Promise<boolean>;
    isCallerBookMember(bookId: string): Promise<boolean>;
    isCallerPermanentAdmin(bookId: string): Promise<boolean>;
    listApprovals(): Promise<Array<[Principal, ApprovalStatus]>>;
    rejectExpense(expenseId: string): Promise<MutResult>;
    rejectInventoryItem(itemId: string): Promise<MutResult>;
    rejectJoinRequest(requestId: string): Promise<JoinRequestResult>;
    rejectTransaction(transactionId: string): Promise<MutResult>;
    removeSelfFromBook(bookId: string): Promise<JoinRequestResult>;
    removeUserFromBook(bookId: string, principalText: string): Promise<JoinRequestResult>;
    requestApproval(): Promise<void>;
    requestJoinBook(bookId: string): Promise<JoinRequestResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAccountingBooks(name: string): Promise<Array<AccountingBook>>;
    searchCustomers(bookId: string, searchTerm: string): Promise<Array<Customer>>;
    searchInventory(bookId: string, searchTerm: string): Promise<Array<InventoryItem>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    transferInventory(bookId: string, itemId: string, fromLocationId: string, toLocationId: string, quantity: bigint, unit: string): Promise<MutResult>;
    updateBookSettings(bookId: string, settings: BookSettings): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateCustomer(customer: Customer): Promise<MutResult>;
    updateInventoryItem(item: InventoryItem): Promise<MutResult>;
    updateSystemSettings(settings: SystemSettings): Promise<void>;
}
import type { AgingBucket as _AgingBucket, AnalyticsExtended as _AnalyticsExtended, ApprovalStatus as _ApprovalStatus, AuditLogEntry as _AuditLogEntry, BookSettings as _BookSettings, CustomerStatement as _CustomerStatement, DraftPurchaseOrder as _DraftPurchaseOrder, JoinRequest as _JoinRequest, JoinRequestResult as _JoinRequestResult, MutResult as _MutResult, ScheduledSummary as _ScheduledSummary, SystemSettings as _SystemSettings, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: Customer): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addExpense(arg0: Expense): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTransaction(arg0: Transaction): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveExpense(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approveExpense(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveExpense(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveInventoryItem(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approveInventoryItem(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveInventoryItem(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveJoinRequest(arg0: string, arg1: boolean): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJoinRequest(arg0, arg1);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJoinRequest(arg0, arg1);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveTransaction(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTransaction(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTransaction(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeUserRole(arg0: string, arg1: string, arg2: boolean): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changeUserRole(arg0, arg1, arg2);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeUserRole(arg0, arg1, arg2);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAccountingBook(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccountingBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccountingBook(arg0);
            return result;
        }
    }
    async createLocation(arg0: string, arg1: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocation(arg0, arg1);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocation(arg0, arg1);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBook(arg0: string): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLocation(arg0: string, arg1: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLocation(arg0, arg1);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLocation(arg0, arg1);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTransaction(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async dismissDraftPurchaseOrder(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissDraftPurchaseOrder(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissDraftPurchaseOrder(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgingReport(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<AgingBucket>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgingReport(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgingReport(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBooks(): Promise<Array<AccountingBook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return result;
        }
    }
    async getAllJoinRequests(): Promise<Array<JoinRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJoinRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJoinRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsExtended(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: AnalyticsExtended;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsExtended(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsExtended(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<AuditLogEntry>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(arg0);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(arg0);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookMembers(arg0);
            return result;
        }
    }
    async getBookMembersWithNames(arg0: string): Promise<Array<[Principal, string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookMembersWithNames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookMembersWithNames(arg0);
            return result;
        }
    }
    async getBookSettings(arg0: string): Promise<{
        __kind__: "ok";
        ok: BookSettings;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookSettings(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookSettings(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerNames(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerNames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerNames(arg0);
            return result;
        }
    }
    async getCustomerStatement(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: CustomerStatement;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerStatement(arg0, arg1);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerStatement(arg0, arg1);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers(arg0);
            return result;
        }
    }
    async getDashboardMetrics(arg0: string): Promise<{
        pendingCount: bigint;
        inventoryItems: bigint;
        customersWithDebt: bigint;
        grossMargin: bigint;
        lowStockCount: bigint;
        totalOutstandingDebt: bigint;
        recentTransactions: Array<Transaction>;
        totalInflows: bigint;
        lowStockItems: Array<[string, bigint, bigint]>;
        totalCustomers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardMetrics(arg0);
            return result;
        }
    }
    async getDraftPurchaseOrders(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<DraftPurchaseOrder>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraftPurchaseOrders(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraftPurchaseOrders(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses(arg0);
            return result;
        }
    }
    async getGrossMarginByPeriod(arg0: string, arg1: bigint, arg2: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrossMarginByPeriod(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrossMarginByPeriod(arg0, arg1, arg2);
            return result;
        }
    }
    async getInventory(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory(arg0);
            return result;
        }
    }
    async getInventoryByLocation(arg0: string, arg1: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryByLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryByLocation(arg0, arg1);
            return result;
        }
    }
    async getInventoryItemNames(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItemNames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItemNames(arg0);
            return result;
        }
    }
    async getInventoryTransfers(arg0: string): Promise<Array<InventoryTransfer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryTransfers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryTransfers(arg0);
            return result;
        }
    }
    async getJoinRequestStatus(arg0: Principal, arg1: string): Promise<ApprovalStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoinRequestStatus(arg0, arg1);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoinRequestStatus(arg0, arg1);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocations(arg0: string): Promise<Array<Location>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocations(arg0);
            return result;
        }
    }
    async getLowStockAlerts(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockAlerts(arg0);
            return result;
        }
    }
    async getOrGenerateScheduledSummary(arg0: string): Promise<{
        __kind__: "ok";
        ok: ScheduledSummary;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrGenerateScheduledSummary(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrGenerateScheduledSummary(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutstandingCredits(arg0: string): Promise<{
        customersWithDebt: bigint;
        totalOutstanding: number;
        outstandingCredits: Array<{
            balance: number;
            debtor: string;
            totalOwed: number;
            amountPaid: number;
            paybackDate: Time;
        }>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutstandingCredits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutstandingCredits(arg0);
            return result;
        }
    }
    async getPendingExpenses(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingExpenses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingExpenses(arg0);
            return result;
        }
    }
    async getPendingInventory(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingInventory(arg0);
            return result;
        }
    }
    async getPendingJoinRequests(): Promise<Array<JoinRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingJoinRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingJoinRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTransactions(arg0);
            return result;
        }
    }
    async getRecentTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentTransactions(arg0);
            return result;
        }
    }
    async getSystemSettings(): Promise<SystemSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemSettings();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemSettings();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopItemsAndCustomers(arg0: string): Promise<{
        topItems: Array<{
            sku: string;
            grossProfit: number;
            totalUnitsSold: bigint;
            brand: string;
        }>;
        topCustomers: Array<{
            name: string;
            lastSaleDate: Time;
            totalSpent: number;
        }>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopItemsAndCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopItemsAndCustomers(arg0);
            return result;
        }
    }
    async getTransactionStatistics(arg0: string): Promise<{
        sales: number;
        creditSales: number;
        purchases: number;
        creditPurchases: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionStatistics(arg0);
            return result;
        }
    }
    async getTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return result;
        }
    }
    async getTransactionsByType(arg0: string, arg1: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(arg0, arg1);
            return result;
        }
    }
    async getUserBooks(): Promise<Array<AccountingBook>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBooks();
            return result;
        }
    }
    async getUserDisplayName(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDisplayName(arg0);
            return result;
        }
    }
    async getUserJoinRequests(): Promise<Array<[string, ApprovalStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJoinRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJoinRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isCallerBookAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerBookAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerBookAdmin(arg0);
            return result;
        }
    }
    async isCallerBookMember(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerBookMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerBookMember(arg0);
            return result;
        }
    }
    async isCallerPermanentAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerPermanentAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerPermanentAdmin(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<[Principal, ApprovalStatus]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectExpense(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectExpense(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectExpense(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectInventoryItem(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectInventoryItem(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectInventoryItem(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectJoinRequest(arg0: string): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectJoinRequest(arg0);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectJoinRequest(arg0);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectTransaction(arg0: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTransaction(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTransaction(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeSelfFromBook(arg0: string): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSelfFromBook(arg0);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSelfFromBook(arg0);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeUserFromBook(arg0: string, arg1: string): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUserFromBook(arg0, arg1);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUserFromBook(arg0, arg1);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestJoinBook(arg0: string): Promise<JoinRequestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestJoinBook(arg0);
                return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestJoinBook(arg0);
            return from_candid_JoinRequestResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAccountingBooks(arg0: string): Promise<Array<AccountingBook>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAccountingBooks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAccountingBooks(arg0);
            return result;
        }
    }
    async searchCustomers(arg0: string, arg1: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCustomers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCustomers(arg0, arg1);
            return result;
        }
    }
    async searchInventory(arg0: string, arg1: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchInventory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchInventory(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async transferInventory(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferInventory(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferInventory(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookSettings(arg0: string, arg1: BookSettings): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookSettings(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookSettings(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: Customer): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInventoryItem(arg0: InventoryItem): Promise<MutResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0);
                return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0);
            return from_candid_MutResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSystemSettings(arg0: SystemSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSystemSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSystemSettings(arg0);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_JoinRequestResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinRequestResult): JoinRequestResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_JoinRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinRequest): JoinRequest {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MutResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MutResult): MutResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApprovalStatus]): ApprovalStatus | null {
    return value.length === 0 ? null : from_candid_ApprovalStatus_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemSettings]): SystemSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    user: Principal;
    bookId: string;
    requestedAt: _Time;
}): {
    status: ApprovalStatus;
    user: Principal;
    bookId: string;
    requestedAt: Time;
} {
    return {
        status: from_candid_ApprovalStatus_n11(_uploadFile, _downloadFile, value.status),
        user: value.user,
        bookId: value.bookId,
        requestedAt: value.requestedAt
    };
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ApprovalStatus]): [string, ApprovalStatus] {
    return [
        value[0],
        from_candid_ApprovalStatus_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _ApprovalStatus]): [Principal, ApprovalStatus] {
    return [
        value[0],
        from_candid_ApprovalStatus_n11(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnalyticsExtended;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AnalyticsExtended;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AuditLogEntry>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AuditLogEntry>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookSettings;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BookSettings;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CustomerStatement;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CustomerStatement;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_DraftPurchaseOrder>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<DraftPurchaseOrder>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ScheduledSummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ScheduledSummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AgingBucket>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AgingBucket>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ApprovalStatus]>): Array<[string, ApprovalStatus]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _ApprovalStatus]>): Array<[Principal, ApprovalStatus]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JoinRequest>): Array<JoinRequest> {
    return value.map((x)=>from_candid_JoinRequest_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
